### ISSUE TITLE
DDT: unbought Take This equipment listed in Missing Equipment

### ISSUE THREAD

**Issue by goldfndr** [Alys/tools-for-habitrpg#33]
I've _earned_ the Take This Shield. It's showing in the DDT's Missing Equipment tab, but I'm not missing it -- I just haven't bought it (for 0 gold) yet.

The Cloak of Wickedness et al are available on the web site and not listed in the DDT's Missing Equipment, so this functionality is partially working.

**Comment by Alys** [comment]
It is actually working correctly; it just appears to be inconsistent
because the Take This gear is handled differently by Habitica itself.

The Missing Equipment is any gear that you have previously owned
(regardless of whether you bought it with gold or gems, or were given it
for free) and which you then lost for any reason (e.g., from death or
Reset).

The new Grand Gala gear will never appear there until you have bought it
because until then, you haven't owned it. It appears in your Rewards column
only because Habitica has made it appear there for everyone.

The Take This gear is a special case within Habitica. For the first Take
This challenge, we gave the gear to the participants by putting it directly
into their Equipment page, without them needing to buy it. Many players
were confused by that because they didn't notice it there, so for the more
recent challenges, we've placed the gear in their Rewards column to be
bought for zero gold. However it's not placed there in the same way as the
Grand Gala gear is because then it would be available to all players.
Instead, we put the Take This gear into the accounts of the participants as
if they had previously bought it and then lost it. This allows them to "buy
it back" without allowing anyone else to buy it. Because of this, it
appears in the Data Display Tool's Missing Equipment section - from a
technical perspective, it is in fact missing equipment, exactly as if it
had been bought and lost due to death.

I can't make the DDT treat the Take This gear differently because it is
impossible for the DDT to tell whether you haven't yet "bought" the gear
for the first time, or have bought it and then lost it - there is no
difference in the data for those two situations.

I also consider it to be correct that it's treated as Missing Equipment
until you buy it because you do own it in the sense that it will always be
available to you if you choose to buy it, but you do not own it in the
sense of being able to wear it.
