### ISSUE TITLE
Drop Cap appears and never disappears

### ISSUE THREAD

**Issue by cosmiccdev** [Alys/tools-for-habitrpg#51]
Currently, the drop cap dashboard icon only appears when the user opens the `Drops Received Today` tab and never disappears.

Is this the intended functionality?

If not, I would be more than happy to make a PR fixing it.

**Comment by Alys** [comment]
It's intentional, but thank you for asking and offering! :)

I had feedback from some players who prefer not to know how many drops they've had or whether their drop cap has been reached for the day (e.g., because that can reduce motivation to do more tasks), so the drop cap dashboard tile only appears if you've chosen to look at your Drops Received Today data.
